services: docker
language: bash

cache:
  directories:
    - ${HOME}/.local/bin
    - ${HOME}/.local/lib

branches:
  only:
    - master

env:
  - ROS_DISTRO=kinetic ALPINE_VERSION=3.7 ROS_PYTHON_VERSION=2
  - ROS_DISTRO=melodic ALPINE_VERSION=3.8 ROS_PYTHON_VERSION=2
  - ROS_DISTRO=noetic ALPINE_VERSION=3.11 ROS_PYTHON_VERSION=3 PACKAGE_LIST=package.list.noetic

before_install:
  - pip install --upgrade --user awscli gh-pr-comment
  - echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

install:
  - make build-updater
  - |
    echo machine github.com > ${HOME}/.netrc \
    && echo login ${TRAVIS_BOT_GITHUB_TOKEN} >> ${HOME}/.netrc \
    && echo machine api.github.com >> ${HOME}/.netrc \
    && echo login ${TRAVIS_BOT_GITHUB_TOKEN} >> ${HOME}/.netrc

script:
  - make dry-run

deploy:
  provider: script
  skip_cleanup: true
  script: make run
  on:
    branch: master
