name: update_impl

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - ROS_DISTRO=melodic ALPINE_VERSION=3.8 ROS_PYTHON_VERSION=2
          - ROS_DISTRO=noetic ALPINE_VERSION=3.11 ROS_PYTHON_VERSION=3
          - ROS_DISTRO=noetic ALPINE_VERSION=3.14 ROS_PYTHON_VERSION=3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          eval export ${{ matrix.env }}
          make build-updater

      - name: Dry-run
        run: |
          eval export ${{ matrix.env }}
          echo machine github.com > ${HOME}/.netrc \
            && echo login ${{ secrets.SQBOT_GITHUB_TOKEN }} >> ${HOME}/.netrc
          make dry-run
          rm -f ${HOME}/.netrc

      - name: Deploy
        if: |
          (github.event_name == 'push' && github.ref == 'refs/heads/master') ||
          github.event_name == 'schedule' ||
          (github.event_name == 'workflow_dispatch' && !inputs.dry)
        run: |
          eval export ${{ matrix.env }}
          echo machine github.com > ${HOME}/.netrc \
            && echo login ${{ secrets.SQBOT_GITHUB_TOKEN }} >> ${HOME}/.netrc
          make run
          rm -f ${HOME}/.netrc
